#!/bin/bash

# this script is made by kieran. i am not responsible for the deletion of your system.

echo "WARNING: If you use neovim, ensure there is a symlink to it as 'vim'. Otherwise, standard vim will install."
echo "If you plan on installing vim, ensure you have root permissions to the package manager."

# yes/no function
ask_yes_no_quit() {
    local message="$1"
    while true; do
        read -p "$message Y/N: " yn
        case $yn in
            [Yy]* ) echo "You chose Yes."; return 0 ;; # Exit code 0 indicates 'Yes'
            [Nn]* ) echo "You chose No."; exit 1 ;;    # Exit script with exit code 1
            * ) echo "Sorry, didn't understand. Please answer yes or no." ;;
        esac
    done
}

# Prompt the user
ask_yes_no_quit "Do you want to install my vim config?"

parent_directory=$(pwd)

# check if vim exists
if ! command -v vim &> /dev/null
then
	ask_yes_no_quit "Vim is not installed. Install it?"

	pkg_manager=""

	if command -v apt-get &> /dev/null; then
		pkg_manager="apt-get"
	elif command -v dnf &> /dev/null; then
		pkg_manager="dnf"
	elif command -v yum &> /dev/null; then
		pkg_manager="yum"
	elif command -v pacman &> /dev/null; then
		pkg_manager="pacman"
	elif command -v brew &> /dev/null; then
		pkg_manager="brew"
	elif command -v zypper &> /dev/null; then
		pkg_manager="zypper"
	elif command -v emerge &> /dev/null; then
		pkg_manager="emerge"
	elif command -v apk &> /dev/null; then
		pkg_manager="apk"
	elif command -v pkg &> /dev/null; then
		pkg_manager="pkg"
	elif command -v slapt-get &> /dev/null; then
		pkg_manager="slapt-get"
	elif command -v xbps-install &> /dev/null; then
		pkg_manager="xbps-install"
	fi

	case "$pkg_manager" in
		apt-get)
			sudo apt-get update
			sudo apt-get install -y vim
			;;
		dnf)
			sudo dnf install -y vim
			;;
		yum)
			sudo yum install -y vim
			;;
		pacman)
			sudo pacman -S --noconfirm vim
			;;
		brew)
			brew install vim
			;;
		zypper)
			sudo zypper install -y vim
			;;
		emerge)
			sudo emerge -av vim
			;;
		apk)
			sudo apk add vim
			;;
		pkg)
			sudo pkg install -y vim
			;;
		slapt-get)
			sudo slapt-get --install-set vim
			;;
		xbps-install)
			sudo xbps-install -y vim
			;;
		*)
			echo "Unsupported package manager."
			;;
	esac

	mkdir $HOME/.vim
	mkdir $HOME/.vim/bundle
fi
sleep 2

# check if vundle exists
if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
    mkdir -p "$HOME/.vim/bundle"
    git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
fi

# install the config
echo "Deleting .vimrc if it exists."
rm -f $HOME/.vimrc
echo "Copying new .vimrc."
cp $parent_directory/dotfiles/vim/vimrc $HOME/.vimrc
sleep 1
echo "Updating plugins."
vim +PluginInstall +qall
echo "Plugins updated."


make -C $HOME/.vim/bundle/vim-hexokinase/


echo "Good job! My config is installed. Have fun!"
