#!/bin/sh

#system-wide variables

export GTK_THEME=Adwaita-dark
export MOZ_USE_XINPUT2=1
export QT_QPA_PLATFORMTHEME=qt6ct

#ensure xdg portals are running
exec /usr/libexec/xdg-desktop-portal-gtk -r &
exec /usr/libexec/flatpak-portal -r &
exec "sh -c 'sleep 5;exec /usr/libexec/xdg-desktop-portal -r'" &

#keybinds
sudo setkeycodes 6c 172 &

#compositor
xscreensaver --no-splash & picom &

#background
feh --bg-fill /home/kiki/Media/Photos/Screenshots/Backgrounds/wall-0.jpg &

#start dwm
dbus-launch /usr/local/bin/dwm & #shitty dwm

#sound, conky, discord
gentoo-pipewire-launcher & conky & arrpc
