#!/bin/sh

if [ "$(pamixer --get-mute)" = true ]; then
    echo "0%"
    exit
fi

vol="$(pamixer --get-volume)"
[ $? -ne 0 ] && [ -z "$vol" ] && exit 1

echo "$vol%"
#if [ "$vol" -gt 40 ]; then
#    echo "HIGH "
#elif [ "$vol" -gt 15 ]; then
#    echo " "
#else
#    echo " "
#fi
