#!/bin/sh

# put svkbd binary location below
#svkbd="svkbd-mobile-plain"
#svkbd="svkbd-mobile-simple"
svkbd="svkbd-sxmo"
#svkbd="svkbd-en"

# code
if pgrep -x $svkbd > /dev/null 
then
	echo "Destorying SVKBD"
	exec pkill $svkbd &
else
	echo "Starting SVKBD"
	exec $svkbd &
fi

